const programmedMessages = [
{ time: "00:00:00", name: "Nubia", text: "Nossa, não sabia disso." },
{ time: "00:00:33", name: "Katiane", text: "Verdade, faz todo sentido." },
{ time: "00:01:11", name: "Dani", text: "Verdade, realmente." },
{ time: "00:01:56", name: "Samanta", text: "Verdade, entendi." },
{ time: "00:02:46", name: "Manu", text: "Déficit calórico é muito difícil de manter." },
{ time: "00:03:19", name: "Pietra", text: "Muito boa essa explicação." },
{ time: "00:03:58", name: "Luci", text: "Muito boa compreendi Douglas." },
{ time: "00:04:40", name: "Juliana", text: "Estou adorando a aula, muito esclarecedora." },
{ time: "00:05:14", name: "Isa", text: "Anotando tudo aqui, dicas de ouro!" },
{ time: "00:05:47", name: "Angela", text: "Sempre tive curiosidade sobre esses hormônios." },
{ time: "00:06:17", name: "Juventite", text: "Que perigo comprar essas coisas da China!" },
{ time: "00:06:55", name: "Juventite", text: "Eu passo o dia todo sem comer e a noite quero comer tudo." },
{ time: "00:07:39", name: "Manu", text: "Ganhar massa é difícil." },
{ time: "00:08:26", name: "Laura", text: "Exatamente isso, a fome a noite é terrível." },
{ time: "00:09:11", name: "Iara", text: "Realmente perigoso comprar da China!" },
{ time: "00:10:01", name: "Iracelma", text: "Eu comecei a treinar e parei várias vezes." },
{ time: "00:10:50", name: "Zenia", text: "Que risco comprar produtos de lá!" },
{ time: "00:11:24", name: "Ana", text: "Que novidade para mim!" },
{ time: "00:11:57", name: "Fabia", text: "Não imaginava isso!" },
{ time: "00:12:29", name: "Paula", text: "Realmente, faz muito sentido." },
{ time: "00:13:06", name: "Iara", text: "Que aula incrível, muito clara!" },
{ time: "00:13:38", name: "Fatima", text: "Sério que o treino é só 20%? Chocada!" },
{ time: "00:14:26", name: "Caleane", text: "A fome noturna é realmente terrível!" },
{ time: "00:15:04", name: "simone", text: "Adorando essa explicação, Douglas!" },
{ time: "00:15:40", name: "Renira", text: "Explicação muito clara, Douglas!" },
{ time: "00:16:14", name: "Ana", text: "Verdade, é muito perigoso mesmo!" },
{ time: "00:17:02", name: "Rubia", text: "Salvando essas dicas valiosas!" },
{ time: "00:17:41", name: "Ydiara", text: "Anotando cada palavra, muito bom!" },
{ time: "00:18:20", name: "Angela", text: "Verdade, agora entendi." },
{ time: "00:18:51", name: "flaviane", text: "Que informação importante!" },
{ time: "00:19:27", name: "flaviane", text: "Muito bom, muito esclarecedor!" },
{ time: "00:20:17", name: "Ydiara", text: "Faz total sentido mesmo." },
{ time: "00:21:05", name: "Caleane", text: "Que explicação excelente!" },
{ time: "00:21:37", name: "Paula", text: "Que conteúdo de qualidade!" },
{ time: "00:22:26", name: "Luci", text: "Concordo demais com isso!" },
{ time: "00:23:15", name: "Luci", text: "Aprendi algo novo aqui." },
{ time: "00:24:05", name: "Angela", text: "Muito bem explicado mesmo!" },
{ time: "00:24:41", name: "Pri", text: "Passo o dia sem comer e a noite quero devorar tudo!" },
{ time: "00:25:16", name: "Jucelina", text: "Dicas de ouro mesmo, Douglas!" },
{ time: "00:25:47", name: "Manu", text: "Nossa, não sabia disso." },
{ time: "00:26:23", name: "Lara", text: "A dieta é o meu maior desafio." },
{ time: "00:26:55", name: "Silva", text: "Cuidado com produtos importados!" },
{ time: "00:27:26", name: "Sara", text: "Estou adorando a aula, muito esclarecedora." },
{ time: "00:27:57", name: "Ana", text: "Isso mesmo, a fome da noite é horrível." },
{ time: "00:28:27", name: "Samanta", text: "Eu também fico sem comer e depois quero comer tudo!" },
{ time: "00:29:04", name: "Ana", text: "Que novidade para mim!" },
{ time: "00:29:35", name: "Rafaela", text: "Chocada que hormônio não é o principal!" },
{ time: "00:30:13", name: "Neli", text: "Guardando essas informações!" },
{ time: "00:30:47", name: "Maisa", text: "Adorei essa explicação!" },
{ time: "00:31:22", name: "Jucelina", text: "Não imaginava isso!" },
{ time: "00:32:12", name: "Neli", text: "Verdade, faz todo sentido." },
{ time: "00:32:57", name: "Silva", text: "Que informação importante!" },
{ time: "00:33:35", name: "Samanta", text: "Muito boa essa explicação." },
{ time: "00:34:20", name: "Maisa", text: "Realmente, faz muito sentido." },
{ time: "00:34:54", name: "Ana", text: "Que aula incrível, muito clara!" },
{ time: "00:35:25", name: "Katianne", text: "Também comecei e parei várias vezes!" },
{ time: "00:36:03", name: "Lucia", text: "Verdade, a fome à noite é o pior!" },
{ time: "00:36:45", name: "Katiane", text: "Eu durmo 6 horas e acordo bem." },
{ time: "00:37:18", name: "Rubia", text: "Aprendi algo novo aqui." },
{ time: "00:38:08", name: "Ana", text: "Anotando tudo aqui, dicas de ouro!" },
{ time: "00:38:46", name: "Angela", text: "Essas canetas estão na moda mesmo, todo mundo falando." },
{ time: "00:39:34", name: "simone", text: "Verdade, agora entendi." },
{ time: "00:40:17", name: "Neli", text: "Que perigo comprar essas coisas da China!" },
{ time: "00:40:53", name: "Katianne", text: "Faz total sentido mesmo." },
{ time: "00:41:36", name: "Jucelia", text: "Eu também já comecei e desisti várias vezes." },
{ time: "00:42:20", name: "Luci", text: "Adorando essa explicação, Douglas!" },
{ time: "00:42:59", name: "flaviane", text: "Muito bom, muito esclarecedor!" },
{ time: "00:43:48", name: "Pri", text: "Salvando essas dicas valiosas!" },
{ time: "00:44:23", name: "Iara", text: "Mesma história, comecei e parei várias vezes." },
{ time: "00:45:05", name: "Isa", text: "Eu quero hipertrofia, perna definida!" },
{ time: "00:45:43", name: "Regina", text: "Concordo demais com isso!" },
{ time: "00:46:23", name: "Juventite", text: "Verdade, faz todo sentido." },
{ time: "00:46:59", name: "Lucia", text: "Realmente, faz muito sentido." },
{ time: "00:47:37", name: "Luci", text: "Anotando cada palavra, muito bom!" },
{ time: "00:48:13", name: "Neli", text: "Eu achava que o treino era o mais importante." },
{ time: "00:48:50", name: "Neli", text: "Que conteúdo de qualidade!" },
{ time: "00:49:36", name: "Katianne", text: "Meu maior desafio é manter a dieta!" },
{ time: "00:50:19", name: "Juventite", text: "Realmente, essas canetas estão em alta!" },
{ time: "00:50:50", name: "🤖Suporte", text: "Segue o link da agenda www.dougleao.com/web/agenda/" },
{ time: "00:51:28", name: "Renira", text: "Este é o link para agendar?" },
{ time: "00:52:14", name: "🤖Suporte", text: "Segue o link da agenda www.dougleao.com/web/agenda/" },
{ time: "00:52:54", name: "Pietra", text: "Verdade, agora entendi." },
{ time: "00:53:34", name: "Samanta", text: "Link do instagram da Doutora: www.instagram.com/dranathany/" },
{ time: "00:54:05", name: "Luci", text: "Dicas de ouro mesmo, Douglas!" },
{ time: "00:54:44", name: "Ana", text: "Não imaginava isso!" },
{ time: "00:55:17", name: "Samanta", text: "Concordo, a fome noturna é terrível." },
{ time: "00:55:53", name: "Flores", text: "A alimentação é onde eu mais erro." },
{ time: "00:56:28", name: "Nubia", text: "Estou adorando a aula, muito esclarecedora." },
{ time: "00:57:00", name: "Juliana", text: "Já passei por isso, comecei e parei demais!" },
{ time: "00:57:42", name: "Sara", text: "Realmente, ganhar massa é complicado!" },
{ time: "00:58:26", name: "Juliana", text: "Que informação importante!" },
{ time: "00:59:07", name: "🤖Suporte", text: "Segue o link pessoa: wwwdougleao.com/web/agenda/" }
];