const programmedMessages = [
{ time: "00:00:00", name: "Zenia", text: "Boa noite! Cheguei!" },
{ time: "00:00:30", name: "Katiane", text: "Boa noite, Douglas! Esperando começar." },
{ time: "00:01:00", name: "Maisa", text: "Vamos lá, ansiosa por hoje!" },
{ time: "00:01:30", name: "Ana", text: "Já compartilhei a live com as amigas." },
{ time: "00:02:00", name: "Iracelma", text: "Boa noite meninas, vamos chegando!" },
{ time: "00:02:30", name: "Juliana", text: "Eu votei em emagrecimento na enquete!" },
{ time: "00:03:00", name: "Julia", text: "Quero hipertrofia, perna definida!" },
{ time: "00:03:30", name: "Samanta", text: "Verdade, o treino não é tudo." },
{ time: "00:04:00", name: "Dani", text: "Estou com papel e caneta na mão." },
{ time: "00:04:30", name: "Regina", text: "Nossa, parabéns pelo vice campeonato!" },
{ time: "00:05:00", name: "Renira", text: "A alimentação é onde eu mais erro." },
{ time: "00:05:30", name: "Silva", text: "Sempre tive curiosidade sobre esses hormônios." },
{ time: "00:06:00", name: "Nubia", text: "Chocada que hormônio não é o principal!" },
{ time: "00:06:30", name: "Ydiara", text: "Eu vim pelo anúncio!" },
{ time: "00:07:00", name: "Fabia", text: "Nossa, eu também era assim na infância, só comia besteira." },
{ time: "00:07:30", name: "Pri", text: "Eu passo o dia todo sem comer e a noite quero comer tudo." },
{ time: "00:08:00", name: "Angela", text: "Eu quero emagrecimento urgente!" },
{ time: "00:08:30", name: "Maisa", text: "Exatamente isso, a fome a noite é terrível." },
{ time: "00:09:00", name: "Pietra", text: "Jejum intermitente nunca deu certo pra mim." },
{ time: "00:09:30", name: "flaviane", text: "Nossa, 130 quilos? Que mudança!" },
{ time: "00:10:00", name: "Lara", text: "Eu comecei a treinar e parei várias vezes." },
{ time: "00:10:30", name: "simone", text: "No começo a gente muda rápido mesmo, depois trava." },
{ time: "00:11:00", name: "Dani", text: "Que evolução incrível, parabéns!" },
{ time: "00:11:30", name: "Margareth", text: "Nossa, você estudou muito, que currículo!" },
{ time: "00:12:00", name: "Paula", text: "Quero ser uma super mulher também kkkk" },
{ time: "00:12:30", name: "Pietra", text: "Estou precisando de mais disposição." },
{ time: "00:13:00", name: "Sara", text: "Eu achava que o treino era o mais importante." },
{ time: "00:13:30", name: "Paula", text: "Sério que o treino é só 20%? Chocada!" },
{ time: "00:14:00", name: "Lucia", text: "A dieta é o meu maior desafio." },
{ time: "00:14:30", name: "Angela", text: "Preciso melhorar meus exames, colesterol tá alto." },
{ time: "00:15:00", name: "Neli", text: "Eu achava que suplemento fazia milagre." },
{ time: "00:15:30", name: "Manu", text: "Qual suplemento você indica pra começar?" },
{ time: "00:16:00", name: "simone", text: "Vou focar no básico então." },
{ time: "00:16:30", name: "Katiane", text: "Tenho 45 anos, a menopausa tá acabando comigo." },
{ time: "00:17:00", name: "Rubia", text: "Reposição hormonal mudou minha vida." },
{ time: "00:17:30", name: "Caleane", text: "Eu sou dos 63% que desiste logo kkkk" },
{ time: "00:18:00", name: "Luci", text: "Muito triste esses dados de obesidade." },
{ time: "00:18:30", name: "Fatima", text: "A indústria só quer a gente doente mesmo." },
{ time: "00:19:00", name: "Isa", text: "Verdade, remédio é caro e não resolve a causa." },
{ time: "00:19:30", name: "Iracelma", text: "Que resultado incrível desse seu aluno!" },
{ time: "00:20:00", name: "Sara", text: "Agora entendi a diferença de hipertrofia e emagrecimento." },
{ time: "00:20:30", name: "Iara", text: "Eu quero perder gordura e definir." },
{ time: "00:21:00", name: "Jucelina", text: "Déficit calórico é muito difícil de manter." },
{ time: "00:21:30", name: "Ydiara", text: "Quero saber esse segredo de fazer os dois ao mesmo tempo!" },
{ time: "00:22:00", name: "Layz", text: "Eu só quero qualidade de vida mesmo." },
{ time: "00:22:30", name: "Regina", text: "Estou adorando a aula, muito esclarecedora." },
{ time: "00:23:00", name: "Iara", text: "Eu sempre pesquiso no Google antes de ir no médico kkkk" },
{ time: "00:23:30", name: "Dani", text: "Inteligência artificial não substitui um bom profissional." },
{ time: "00:24:00", name: "Lara", text: "Eu já tentei usar o ChatGPT pra dieta, não deu certo." },
{ time: "00:24:30", name: "Laura", text: "Essas canetas estão na moda mesmo, todo mundo falando." },
{ time: "00:25:00", name: "Lara", text: "Ozempic é muito caro!" },
{ time: "00:25:30", name: "Meire", text: "Conheço gente que passou muito mal com essas canetas." },
{ time: "00:26:00", name: "Manu", text: "Perder músculo é o pior, a gente fica flácida." },
{ time: "00:26:30", name: "Laura", text: "Já fiz a dieta do ovo, passei mal." },
{ time: "00:27:00", name: "Margareth", text: "Dieta da lua eu já fiz também kkkk" },
{ time: "00:27:30", name: "simone", text: "O básico que funciona, né?" },
{ time: "00:28:00", name: "Neli", text: "Não existe milagre, tem que ter constância." },
{ time: "00:28:30", name: "Ana Clara", text: "Nunca ouvi falar desses peptídios." },
{ time: "00:29:00", name: "Lara", text: "Que perigo comprar essas coisas da China!" },
{ time: "00:29:30", name: "Neli", text: "Deus me livre injetar algo que não sei o que é." },
{ time: "00:30:00", name: "Regina", text: "Saúde em primeiro lugar sempre." },
{ time: "00:30:30", name: "Juventite", text: "Gostei dessa divisão de 4 refeições." },
{ time: "00:31:00", name: "Paula", text: "Eu sinto muita fome a noite, vou testar isso." },
{ time: "00:31:30", name: "Rafaela", text: "Treinar 4 vezes na semana é o ideal pra mim." },
{ time: "00:32:00", name: "Ydiara", text: "Eu odeio cardio, mas sei que preciso." },
{ time: "00:32:30", name: "Fabia", text: "Anotando tudo aqui, dicas de ouro!" },
{ time: "00:33:00", name: "Iara", text: "Meu sono é péssimo, acordo cansada." },
{ time: "00:33:30", name: "Katianne", text: "Dormir bem faz toda a diferença no emagrecimento." },
{ time: "00:34:00", name: "Jucelia", text: "Eu durmo 6 horas e acordo bem." },
{ time: "00:34:30", name: "Flores", text: "Qual o link da agenda, Douglas? https://dougleao.com/web/agenda/" },
{ time: "00:35:00", name: "Pri", text: "Vou agendar minha consulta com certeza! https://dougleao.com/web/agenda/" },
{ time: "00:35:30", name: "Meire", text: "Passa o Instagram da sua esposa! https://www.instagram.com/dranathany/" },
{ time: "00:36:00", name: "Angelina", text: "Já vou seguir ela lá. https://www.instagram.com/dranathany/" },
{ time: "00:36:30", name: "Jucelia", text: "Muito obrigada pela aula, foi top!" },
];